/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fasa.MeuProjeto_5.Gui;

import br.edu.fasa.MeuProjeto.Dao.CaoDao;
import br.edu.fasa.MeuProjeto.Util.Util;
import br.edu.fasa.MeuProjeto_5.Model.Cao;
import javax.swing.JOptionPane;

/**
 *
 * @author paulocesar
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Cao cachorro = new Cao();
    ;
    private CaoDao caoDao;

    public void preencheTela(Cao obj) {

        jTCod.setText(String.valueOf(obj.getCod()));
        jTNome.setText(obj.getNome());
        jTRaca.setText(obj.getRaca());
        jTCor.setText(obj.getCor());
        jTPeso.setText(String.valueOf(obj.getPeso()));
        jTIdade.setText(String.valueOf(obj.getIdade()));
        jTLatido.setText(obj.getLatido());

        cachorro.setCod(Integer.parseInt(jTCod.getText()));

        Util.getPrincipal().setVisible(true);

    }
    
    private void limpaTelaPrincipal(){
        jTCod.setText("");
        jTNome.setText("");
        jTRaca.setText("");
        jTCor.setText("");
        jTPeso.setText("");
        jTIdade.setText("");
        jTLatido.setText("");
    }

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jPTelaPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTRaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTIdade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTLatido = new javax.swing.JTextField();
        jBCad = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTCod = new javax.swing.JTextField();
        jBApagar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setForeground(new java.awt.Color(153, 255, 153));

        jPTelaPrincipal.setBackground(new java.awt.Color(204, 204, 255));
        jPTelaPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fasa Pet Shop", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPTelaPrincipal.setForeground(new java.awt.Color(255, 0, 51));
        jPTelaPrincipal.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Raça:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Peso:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Idade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Latido:");

        jBCad.setText("Cadastrar");
        jBCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadActionPerformed(evt);
            }
        });

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Modificar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Código");

        jTCod.setEditable(false);

        jBApagar.setText("Apagar");
        jBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelaPrincipalLayout = new javax.swing.GroupLayout(jPTelaPrincipal);
        jPTelaPrincipal.setLayout(jPTelaPrincipalLayout);
        jPTelaPrincipalLayout.setHorizontalGroup(
            jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaPrincipalLayout.createSequentialGroup()
                        .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTRaca, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                        .addComponent(jTCor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTPeso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTIdade, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTLatido, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(jBAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(jBApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBCad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(jTCod))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))))
        );
        jPTelaPrincipalLayout.setVerticalGroup(
            jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNome)
                    .addComponent(jTCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jBApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(5, 5, 5)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTLatido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed

        caoDao = new CaoDao();
        int a = 0;

        if (cachorro.getCod() == 0) {
            Util.getConsulta().setVisible(true);
            

        } else if (cachorro.getCod() != 0) {
                                    
            cachorro.setNome(jTNome.getText());
            cachorro.setRaca(jTRaca.getText());
            cachorro.setCor(jTCor.getText());
            cachorro.setPeso(Float.parseFloat(jTPeso.getText()));
            cachorro.setIdade(Integer.parseInt(jTIdade.getText()));
            cachorro.setLatido(jTLatido.getText());

            a = caoDao.atualizar(cachorro);
        }

        if (a == 1) {
            
            JOptionPane.showMessageDialog(null,
                    "Atualização Efetuada com Sucesso!!", "Atualizar",
                    JOptionPane.INFORMATION_MESSAGE);
            limpaTelaPrincipal();
        }
        if (a == 2) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao Atualizar", "Atualizar",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        Util.getConsulta().setVisible(true);

    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadActionPerformed

        cachorro = new Cao();
        caoDao = new CaoDao();

        cachorro.setNome(jTNome.getText());
        cachorro.setRaca(jTRaca.getText());
        cachorro.setCor(jTCor.getText());
        cachorro.setPeso(Float.parseFloat(jTPeso.getText()));
        cachorro.setIdade(Integer.parseInt(jTIdade.getText()));
        cachorro.setLatido(jTLatido.getText());

        if (caoDao.inserir(cachorro)) {
            jTCod.setText(String.valueOf(Util.getUltimoCodigo()));
            JOptionPane.showMessageDialog(null,
                    "Cadastro Efetuado com Sucesso!!", "Cadastro",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Erro ao Cadastrar", "Cadastro",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBCadActionPerformed

    private void jBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarActionPerformed
        
        caoDao = new CaoDao();
        int a = 0;

        if (cachorro.getCod() == 0) {
            Util.getConsulta().setVisible(true);
           

        } 
        
        else if (cachorro.getCod() != 0) {            
           
            cachorro.setNome(jTNome.getText());
            cachorro.setRaca(jTRaca.getText());
            cachorro.setCor(jTCor.getText());
            cachorro.setPeso(Float.parseFloat(jTPeso.getText()));
            cachorro.setIdade(Integer.parseInt(jTIdade.getText()));
            cachorro.setLatido(jTLatido.getText());
            
            if(JOptionPane.showConfirmDialog(null, 
                    "Deseja Realmente Excluir o Registro?", "Confirmação", 
                    JOptionPane.YES_NO_OPTION)==0){
                a = caoDao.apagar(cachorro);  
            }            
        }

        if (a == 1) {           
            JOptionPane.showMessageDialog(null,
                    "Registro Excluido com Sucesso!!", "Deletar",
                    JOptionPane.INFORMATION_MESSAGE);
            limpaTelaPrincipal();
        }
        if (a == 2) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao Excluir Registro", "Deletar",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Util.getPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBApagar;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCad;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPTelaPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCod;
    private javax.swing.JTextField jTCor;
    private javax.swing.JTextField jTIdade;
    private javax.swing.JTextField jTLatido;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTPeso;
    private javax.swing.JTextField jTRaca;
    // End of variables declaration//GEN-END:variables
}
